name: Continuous Integration
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  check_formatting_linting_and_unit_tests:
    name: Check Formatting, Linting and Unit Tests
    runs-on: ubuntu-latest

    container:
      image: mldc/tcp:latest
      volumes:
        - ${{ github.workspace }}:/tcp

    env:
      working-directory: /tcp

    steps:
      - uses: 'actions/checkout@v4'

      - name: Check Formatting
        run: poetry run ruff format --check src
        working-directory: ${{ env.working-directory }}

      - name: Check Linting
        run: poetry run ruff check src
        working-directory: ${{ env.working-directory }}

      - name: Unit Tests
        run: poetry run pytest -v src
        working-directory: ${{ env.working-directory }}
